<section>
        <h2 id="logintext">Login</h2>
        <form action="../php/controlAcceso.php" method="POST" id="login">
            <label for="user">Usuario:</label><br>
            <input type="text" id="user" name="user" placeholder="Pepe"><br>
            <label for="password">Contraseña:</label><br>
            <input type="password" id="password" name="password" placeholder="tu contraseña"><br>
            <input class="enviar" type="submit" value="Enviar" />
        </form>


    </section>