/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package encriptar;

import com.mysql.jdbc.Connection;
import conexionSQL.conexionmysql;
import java.io.UnsupportedEncodingException;
import java.security.InvalidKeyException;
import java.security.KeyPair;
import java.security.KeyPairGenerator;
import java.security.NoSuchAlgorithmException;
import java.util.Base64;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.crypto.BadPaddingException;
import javax.crypto.Cipher;
import javax.crypto.IllegalBlockSizeException;
import javax.crypto.NoSuchPaddingException;
import javax.crypto.SecretKey;
import javax.crypto.spec.SecretKeySpec;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class Registrarse extends javax.swing.JFrame {

    conexionmysql cc= new conexionmysql();
    Connection con= cc.conexion();
    /**
     * Creates new form Registrarse
     */
    public Registrarse() {
        initComponents();        
        setIconImage(new ImageIcon(getClass().getResource("img/padlock_78356.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNuevoPasss = new javax.swing.JLabel();
        txtNuevoPass = new javax.swing.JPasswordField();
        txtNuevoUsuario = new javax.swing.JTextField();
        txtNuevo = new javax.swing.JLabel();
        txtNuevoPass1 = new javax.swing.JLabel();
        txtRepePass = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CRIPTODRIVE | REGISTRARSE");
        setPreferredSize(new java.awt.Dimension(788, 519));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Montserrat", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 204));
        jLabel1.setText("CRIPTODRIVE");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, -1, -1));

        txtNuevoPasss.setFont(new java.awt.Font("Montserrat", 0, 24)); // NOI18N
        txtNuevoPasss.setForeground(new java.awt.Color(0, 153, 204));
        txtNuevoPasss.setText("CONTRASEÑA: ");
        getContentPane().add(txtNuevoPasss, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, -1, -1));

        txtNuevoPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNuevoPassActionPerformed(evt);
            }
        });
        getContentPane().add(txtNuevoPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 250, 182, 30));

        txtNuevoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNuevoUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(txtNuevoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, 182, 30));

        txtNuevo.setFont(new java.awt.Font("Montserrat", 0, 24)); // NOI18N
        txtNuevo.setForeground(new java.awt.Color(0, 153, 204));
        txtNuevo.setText("NOMBRE USUARIO: ");
        txtNuevo.setToolTipText("");
        getContentPane().add(txtNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, -1, -1));

        txtNuevoPass1.setFont(new java.awt.Font("Montserrat", 0, 24)); // NOI18N
        txtNuevoPass1.setForeground(new java.awt.Color(0, 153, 204));
        txtNuevoPass1.setText("REPETIR CONTRASEÑA: ");
        getContentPane().add(txtNuevoPass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, -1, -1));
        getContentPane().add(txtRepePass, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 300, 182, 30));

        jButton1.setBackground(new java.awt.Color(0, 153, 204));
        jButton1.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jButton1.setText("REGISTRARSE");
        jButton1.setToolTipText("");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 370, 120, 56));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/encriptar/img/padlock_78356.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 40, -1, -1));

        jLabel4.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 204));
        jLabel4.setText("| REGISTRARSE |");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/encriptar/img/istockphoto-1143434145-170667a.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 670));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNuevoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNuevoUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNuevoUsuarioActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        boolean accede= true;
        String nombre= txtNuevoUsuario.getText();
        String pass= String.valueOf(txtNuevoPass.getPassword());
        String pass2= String.valueOf(txtRepePass.getPassword());
        
        if(nombre.equals("") || nombre.equals(" ") || nombre.length()==0){
            accede=false;
        }
        
        if(pass.length()!=16){
            accede=false;
        }
        else if(!pass.equals(pass2)){
            accede=false;
        }
        
        if(accede){
            
            String publica=null;
            String privada= null;
            
            try {
                //GENERO PAR DE CLAVES
                KeyPairGenerator generadorRSA= KeyPairGenerator.getInstance("RSA");
                generadorRSA.initialize(1024);
                KeyPair claves = generadorRSA.genKeyPair();
                publica= Base64.getEncoder().encodeToString(claves.getPublic().getEncoded());
                
                //ENCRIPTO RSA PRIVADA CON LA CONTRASEÑA MEDIANTE AES
                SecretKey passMontada= new SecretKeySpec(pass.getBytes(("UTF-8")),"AES");
                Cipher en= Cipher.getInstance("AES");
                en.init(Cipher.ENCRYPT_MODE,passMontada);
                byte[] subir_privada= en.doFinal(claves.getPrivate().getEncoded());
                privada= Base64.getEncoder().encodeToString(subir_privada);
                
            } catch (NoSuchAlgorithmException ex) {
                Logger.getLogger(Registrarse.class.getName()).log(Level.SEVERE, null, ex);
            } catch (UnsupportedEncodingException ex) {
                Logger.getLogger(Registrarse.class.getName()).log(Level.SEVERE, null, ex);
            } catch (NoSuchPaddingException ex) {
                Logger.getLogger(Registrarse.class.getName()).log(Level.SEVERE, null, ex);
            } catch (InvalidKeyException ex) {
                Logger.getLogger(Registrarse.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IllegalBlockSizeException ex) {
                Logger.getLogger(Registrarse.class.getName()).log(Level.SEVERE, null, ex);
            } catch (BadPaddingException ex) {
                Logger.getLogger(Registrarse.class.getName()).log(Level.SEVERE, null, ex);
            }
            
                        
            String sql="INSERT INTO usuario (nombre_usuario, password, publica, privada_AES) VALUES ('"+nombre+"',SHA('"+pass+"'),'"+publica+"','"+privada+"'); ";
            
            try{
                java.sql.PreparedStatement pst= con.prepareStatement(sql);
                pst.execute();
                JOptionPane.showMessageDialog(null, "Usuario registrado");
                Acceso ac= new Acceso();
                ac.setVisible(true);
                this.dispose();
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null, "Error "+e.getMessage());
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Parametros mal introducidos");
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtNuevoPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNuevoPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNuevoPassActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registrarse().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel txtNuevo;
    private javax.swing.JPasswordField txtNuevoPass;
    private javax.swing.JLabel txtNuevoPass1;
    private javax.swing.JLabel txtNuevoPasss;
    private javax.swing.JTextField txtNuevoUsuario;
    private javax.swing.JPasswordField txtRepePass;
    // End of variables declaration//GEN-END:variables
}
