// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace UnicarAdmin
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Threading;
    using System.Threading.Tasks;
    using Microsoft.Rest;
    using DefaultConnection;

    /// <summary>
    /// Extension methods for Climatologíasdiarias.
    /// </summary>
    public static partial class ClimatologíasdiariasExtensions
    {
            /// <summary>
            /// Climatologías diarias.
            /// </summary>
            /// Valores climatológicos de todas las estaciones para el rango de fechas
            /// seleccionado. Periodicidad: 1 vez al día.
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='fechaIniStr'>
            /// Fecha Inicial (AAAA-MM-DDTHH:MM:SSUTC)
            /// </param>
            /// <param name='fechaFinStr'>
            /// Fecha Final (AAAA-MM-DDTHH:MM:SSUTC)
            /// </param>
            public static object One(this IClimatologíasdiarias operations, string fechaIniStr, string fechaFinStr)
            {
                return Task.Factory.StartNew(s => ((IClimatologíasdiarias)s).OneAsync(fechaIniStr, fechaFinStr), operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
            }

            /// <summary>
            /// Climatologías diarias.
            /// </summary>
            /// Valores climatológicos de todas las estaciones para el rango de fechas
            /// seleccionado. Periodicidad: 1 vez al día.
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='fechaIniStr'>
            /// Fecha Inicial (AAAA-MM-DDTHH:MM:SSUTC)
            /// </param>
            /// <param name='fechaFinStr'>
            /// Fecha Final (AAAA-MM-DDTHH:MM:SSUTC)
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<object> OneAsync(this IClimatologíasdiarias operations, string fechaIniStr, string fechaFinStr, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.OneWithHttpMessagesAsync(fechaIniStr, fechaFinStr, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

    }
}
