// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace UnicarAdmin
{
    using System;
    using System.Collections.Generic;
    using System.Net.Http;
    using System.Threading;
    using System.Threading.Tasks;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using DefaultConnection;

    /// <summary>
    /// AEMET OpenData es una API REST desarrollado por AEMET que permite la
    /// difusión y la reutilización de la información meteorológica y
    /// climatológica de la Agencia, en el sentido indicado en la Ley
    /// 18/2015, de 9 de julio, por la que se modifica la Ley 37/2007, de 16
    /// de noviembre, sobre reutilización de la información del sector
    /// público. (IMPORTANTE: Para poder realizar peticiones, es necesario
    /// introducir en API Key haciendo clic en el círculo rojo de recurso
    /// REST).
    /// </summary>
    public partial interface IAEMETOpenData : IDisposable
    {
        /// <summary>
        /// The base URI of the service.
        /// </summary>
        Uri BaseUri { get; set; }

        /// <summary>
        /// Gets or sets json serialization settings.
        /// </summary>
        JsonSerializerSettings SerializationSettings { get; }

        /// <summary>
        /// Gets or sets json deserialization settings.
        /// </summary>
        JsonSerializerSettings DeserializationSettings { get; }

        /// <summary>
        /// Subscription credentials which uniquely identify client
        /// subscription.
        /// </summary>
        ServiceClientCredentials Credentials { get; }


        /// <summary>
        /// Gets the IMapassignificativosTiempoactual.
        /// </summary>
        IMapassignificativosTiempoactual MapassignificativosTiempoactual { get; }

        /// <summary>
        /// Gets the IDatosdeobservaciónTiempoactual.
        /// </summary>
        IDatosdeobservaciónTiempoactual DatosdeobservaciónTiempoactual { get; }

        /// <summary>
        /// Gets the IClimatologíasdiarias.
        /// </summary>
        IClimatologíasdiarias Climatologíasdiarias { get; }

            /// <summary>
        /// Avisos de Fenómenos Meteorológicos Adversos. Último.
        /// </summary>
        /// Últimos Avisos de Fenómenos Meteorológicos adversos elaborado
        /// para el área seleccionada.
        /// <param name='area'>
        /// | Código | Área |
        /// |----------|----------|
        /// | esp  | España|
        /// | 61  | Andalucía   |
        /// | 62  | Aragón   |
        /// | 63  | Asturias, Principado de  |
        /// | 64  | Ballears, Illes   |
        /// | 78  | Ceuta   |
        /// | 65  | Canarias   |
        /// | 66  | Cantabria   |
        /// | 67  | Castilla y León   |
        /// | 68  | Castilla - La Mancha   |
        /// | 69  | Cataluña   |
        /// | 77  | Comunitat Valenciana   |
        /// | 70  | Extremadura   |
        /// | 71  | Galicia   |
        /// | 72  | Madrid, Comunidad de    |
        /// | 79  | Melilla   |
        /// | 73  | Murcia, Región de   |
        /// | 74  | Navarra, Comunidad Foral de   |
        /// | 75  | País Vasco |
        /// | 76  | Rioja, La
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<object>> AvisosdeFenómenosMeteorológicosAdversosÚltimoWithHttpMessagesAsync(string area, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Avisos de Fenómenos Meteorológicos Adversos. Archivo.
        /// </summary>
        /// Avisos de Fenómenos Meteorológicos adversos para el rango de
        /// fechas seleccionado (datos desde 18/06/2018).
        /// <param name='fechaIniStr'>
        /// Fecha Inicial (AAAA-MM-DDTHH:MM:SSUTC)
        /// </param>
        /// <param name='fechaFinStr'>
        /// Fecha Final (AAAA-MM-DDTHH:MM:SSUTC)
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<object>> AvisosdeFenómenosMeteorológicosAdversosArchivoWithHttpMessagesAsync(string fechaIniStr, string fechaFinStr, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Mapa de niveles de riesgo estimado meteorológico de incendios
        /// forestales.
        /// </summary>
        /// Último mapa elaborado de niveles de riesgo estimado meteorológico
        /// de incendios forestales para el área pasada por parámetro.
        /// <param name='area'>
        /// | Código | Área |
        /// |----------|----------|
        /// | p  | Península   |
        /// | b  | Baleares   |
        /// | c  | Canarias
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<object>> MapadenivelesderiesgoestimadometeorológicodeincendiosforestalesWithHttpMessagesAsync(string area, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Mapa de niveles de riesgo previsto meteorológico de incendios
        /// forestales.
        /// </summary>
        /// Mapa elaborado de niveles de riesgo estimado meteorológico de
        /// incendios forestales para el día y el área pasados por parámetro.
        /// <param name='dia'>
        /// | Código | Día |
        /// |----------|----------|
        /// | 1  | Mañana   |
        /// | 2  | Pasado Mañana   |
        /// | 3  | Dentro de 3 días
        /// </param>
        /// <param name='area'>
        /// | Código | Área |
        /// |----------|----------|
        /// | p  | Península   |
        /// | b  | Baleares   |
        /// | c  | Canarias
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<object>> MapadenivelesderiesgoprevistometeorológicodeincendiosforestalesWithHttpMessagesAsync(string dia, string area, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// getMunicipio
        /// </summary>
        /// Retorna información específica del municipio de España que se le
        /// pasa como parámetro.
        /// <param name='municipio'>
        /// Municipio
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<object>> GetMunicipioUsingGETWithHttpMessagesAsync(string municipio, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// getMunicipios
        /// </summary>
        /// Retorna todos los municipios de España. Este servicio es útil para
        /// obtener información para utilizar otros elementos de AEMET
        /// OpenData, como por ejemplo, la predicción de municipios para 7
        /// días o por  horas ya que nos retorna el id del municipio que
        /// necesitamos.
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<object>> GetMunicipiosUsingGETWithHttpMessagesAsync(Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Mapas de análisis. Última pasada.
        /// </summary>
        /// Estos mapas muestran la configuración de la presión en superficie
        /// usando isobaras (lineas de igual presión), áreas de alta (A, a) y
        /// baja (B, b) presión y los frentes en Europa y el Atlántico
        /// Norte.El mapa de análisis presenta el estado de la atmósfera a la
        /// hora correspondiente y los fenómenos más relevantes observados en
        /// España. Periodicidad de actualización: cada 12 horas (00, 12).
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<object>> MapasdeanálisisÚltimapasadaWithHttpMessagesAsync(Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Mapas significativos. Tiempo actual.
        /// </summary>
        /// Mapas significativos de ámbito nacional o CCAA, para una fecha
        /// dada y ese mismo día (D+0),  al día siguiente (D+1) o a los dos
        /// días (D+2), en el periodo horario de (00_12) ó (12-24).
        /// <param name='fecha'>
        /// Fecha de elaboración (AAAA-MM-DD)
        /// </param>
        /// <param name='ambito'>
        /// | Código | Ámbito |
        /// |----------|----------|
        /// | esp  | España|
        /// | and  | Andalucía   |
        /// | arn  | Aragón   |
        /// | ast  | Asturias  |
        /// | bal  | Ballears, Illes   |
        /// | coo  | Canarias   |
        /// | can  | Cantabria   |
        /// | cle  | Castilla y León   |
        /// | clm  | Castilla - La Mancha   |
        /// | cat  | Cataluña   |
        /// | val  | Comunitat Valenciana   |
        /// | ext  | Extremadura   |
        /// | gal  | Galicia   |
        /// | mad  | Madrid, Comunidad de    |
        /// | mur  | Murcia, Región de   |
        /// | nav  | Navarra, Comunidad Foral de   |
        /// | pva  | País Vasco |
        /// | rio  | Rioja, La
        /// </param>
        /// <param name='dia'>
        /// | Código de día | Día |
        /// |----------|----------|
        /// | a | D+0 (00-12)  |
        /// | b  | D+0 (00-12)   |
        /// |  c | D+1 (00-12)  |
        /// | d  | D+1 (12-24) |
        /// | e  | D+2 (00-12) |
        /// | f  | D+2 (12-24)
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<object>> MapassignificativosTiempoactualWithHttpMessagesAsync(string fecha, string ambito, string dia, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Datos de observación. Tiempo actual.
        /// </summary>
        /// Datos de observación horarios de las últimas 24 horas todas las
        /// estaciones meteorológicas de las que se han recibido datos en ese
        /// período. Frecuencia de actualización: continuamente.
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<object>> DatosdeobservaciónTiempoactualWithHttpMessagesAsync(Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Mensajes de observación. Último elaborado.
        /// </summary>
        /// Últimos mensajes de observación. Para los SYNOP y TEMP devuelve
        /// los mensajes de las últimas 24 horas y para los CLIMAT de los 40
        /// últimos dias. Se pasa como parámetro el tipo de mensaje que se
        /// desea (tipomensaje). El resultado de la petición es un fichero en
        /// formato tar.gz, que contiene los boletines en formato json y bufr.
        /// <param name='tipomensaje'>
        /// | Código | Tipo de Mensaje |
        /// |----------|----------|
        /// | climat  | climat   |
        /// | synop  | synop   |
        /// | temp  | temp
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<object>> MensajesdeobservaciónÚltimoelaboradoWithHttpMessagesAsync(string tipomensaje, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Predicción CCAA hoy. Tiempo actual.
        /// </summary>
        /// Predicción para la CCAA que se pasa como parámetro con validez
        /// para mismo día que la fecha de petición. En el caso de que en la
        /// fecha de petición este producto todavía no se hubiera elaborado,
        /// se retornará el último elaborado. Actualización continuamente.
        /// <param name='ccaa'>
        /// | Código de CCAA | CCAA |
        /// |----------|----------|
        /// | and  | Andalucía   |
        /// | arn  | Aragón   |
        /// | ast  | Asturias  |
        /// | bal  | Ballears, Illes   |
        /// | coo  | Canarias   |
        /// | can  | Cantabria   |
        /// | cle  | Castilla y León   |
        /// | clm  | Castilla - La Mancha   |
        /// | cat  | Cataluña   |
        /// | val  | Comunitat Valenciana   |
        /// | ext  | Extremadura   |
        /// | gal  | Galicia   |
        /// | mad  | Madrid, Comunidad de    |
        /// | mur  | Murcia, Región de   |
        /// | nav  | Navarra, Comunidad Foral de   |
        /// | pva  | País Vasco |
        /// | rio  | Rioja, La
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<object>> PredicciónCCAAhoyTiempoactualWithHttpMessagesAsync(string ccaa, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Predicción CCAA hoy. Archivo.
        /// </summary>
        /// Predicción para la comunidad autónoma que se pasa como parámetro
        /// (ccaa) con validez para el día de fecha de elaboración que se
        /// pasa como parámetro (fecha). Periodicidad de actualización:
        /// continuamente.
        /// <param name='ccaa'>
        /// | Código de CCAA | CCAA |
        /// |----------|----------|
        /// | and  | Andalucía   |
        /// | arn  | Aragón   |
        /// | ast  | Astrrias  |
        /// | bal  | Ballears, Illes   |
        /// | coo  | Canarias   |
        /// | can  | Cantabria   |
        /// | cle  | Castilla y León   |
        /// | clm  | Castilla - La Mancha   |
        /// | cat  | Cataluña   |
        /// | val  | Comunitat Valenciana   |
        /// | ext  | Extremadura   |
        /// | gal  | Galicia   |
        /// | mad  | Madrid, Comunidad de    |
        /// | mur  | Murcia, Región de   |
        /// | nav  | Navarra, Comunidad Foral de   |
        /// | pva  | País Vasco |
        /// | rio  | Rioja, La
        /// </param>
        /// <param name='fecha'>
        /// Día de elaboración (AAAA-MM-DD)
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<object>> PredicciónCCAAhoyArchivoWithHttpMessagesAsync(string ccaa, string fecha, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Predicción CCAA mañana. Tiempo actual.
        /// </summary>
        /// Predicción para la comunidad autónoma que se pasa como parámetro
        /// para el día siguiente a la fecha de la petición. En el caso de el
        /// producto no se hubiera elaborado todavía en la fecha de petición
        /// se retornará el último producto elaborado. Periodicidad de
        /// actualización: continuamente.
        /// <param name='ccaa'>
        /// | Código de CCAA | CCAA |
        /// |----------|----------|
        /// | and  | Andalucía   |
        /// | arn  | Aragón   |
        /// | ast  | Astrrias  |
        /// | bal  | Ballears, Illes   |
        /// | coo  | Canarias   |
        /// | can  | Cantabria   |
        /// | cle  | Castilla y León   |
        /// | clm  | Castilla - La Mancha   |
        /// | cat  | Cataluña   |
        /// | val  | Comunitat Valenciana   |
        /// | ext  | Extremadura   |
        /// | gal  | Galicia   |
        /// | mad  | Madrid, Comunidad de    |
        /// | mur  | Murcia, Región de   |
        /// | nav  | Navarra, Comunidad Foral de   |
        /// | pva  | País Vasco |
        /// | rio  | Rioja, La
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<object>> PredicciónCCAAmañanaTiempoactualWithHttpMessagesAsync(string ccaa, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Predicción CCAA mañana. Archivo.
        /// </summary>
        /// Predicción para la comunidad autónoma que se pasa como parámetro
        /// (ccaa) con validez para el día siguiente a la fecha de
        /// elaboración que se pasa como parámetro (fecha). Periodicidad de
        /// actualización. continuamente.
        /// <param name='ccaa'>
        /// | Código de CCAA | CCAA |
        /// |----------|----------|
        /// | and  | Andalucía   |
        /// | arn  | Aragón   |
        /// | ast  | Astrrias  |
        /// | bal  | Ballears, Illes   |
        /// | coo  | Canarias   |
        /// | can  | Cantabria   |
        /// | cle  | Castilla y León   |
        /// | clm  | Castilla - La Mancha   |
        /// | cat  | Cataluña   |
        /// | val  | Comunitat Valenciana   |
        /// | ext  | Extremadura   |
        /// | gal  | Galicia   |
        /// | mad  | Madrid, Comunidad de    |
        /// | mur  | Murcia, Región de   |
        /// | nav  | Navarra, Comunidad Foral de   |
        /// | pva  | País Vasco |
        /// | rio  | Rioja, La
        /// </param>
        /// <param name='fecha'>
        /// Día de elaboración (AAAA-MM-DD)
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<object>> PredicciónCCAAmañanaArchivoWithHttpMessagesAsync(string ccaa, string fecha, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Predicción CCAA medio plazo. Tiempo actual.
        /// </summary>
        /// Predicción para la comunidad autónoma que se pasa como parámetro
        /// (ccaa) y con validez para el medio plazo a partir de la fecha de
        /// petición. En el caso de que en el fecha de la petición no se
        /// hubiera generado aún el producto, se retornará el última
        /// elaborado. Periodicidad de actualización: continuamente.
        /// <param name='ccaa'>
        /// | Código de CCAA | CCAA |
        /// |----------|----------|
        /// | and  | Andalucía   |
        /// | arn  | Aragón   |
        /// | ast  | Astrrias  |
        /// | bal  | Ballears, Illes   |
        /// | coo  | Canarias   |
        /// | can  | Cantabria   |
        /// | cle  | Castilla y León   |
        /// | clm  | Castilla - La Mancha   |
        /// | cat  | Cataluña   |
        /// | val  | Comunitat Valenciana   |
        /// | ext  | Extremadura   |
        /// | gal  | Galicia   |
        /// | mad  | Madrid, Comunidad de    |
        /// | mur  | Murcia, Región de   |
        /// | nav  | Navarra, Comunidad Foral de   |
        /// | pva  | País Vasco |
        /// | rio  | Rioja, La
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<object>> PredicciónCCAAmedioplazoTiempoactualWithHttpMessagesAsync(string ccaa, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Predicción CCAA medio plazo. Archivo.
        /// </summary>
        /// Predicción de mediio plazo para la comunidad autónoma que se pasa
        /// como parámetro (ccaa) a partir de la fecha de elaboración que se
        /// pasa como parámetro (fecha). Periodicidad de actualización:
        /// continuamente.
        /// <param name='ccaa'>
        /// | Código de CCAA | CCAA |
        /// |----------|----------|
        /// | and  | Andalucía   |
        /// | arn  | Aragón   |
        /// | ast  | Astrrias  |
        /// | bal  | Ballears, Illes   |
        /// | coo  | Canarias   |
        /// | can  | Cantabria   |
        /// | cle  | Castilla y León   |
        /// | clm  | Castilla - La Mancha   |
        /// | cat  | Cataluña   |
        /// | val  | Comunitat Valenciana   |
        /// | ext  | Extremadura   |
        /// | gal  | Galicia   |
        /// | mad  | Madrid, Comunidad de    |
        /// | mur  | Murcia, Región de   |
        /// | nav  | Navarra, Comunidad Foral de   |
        /// | pva  | País Vasco |
        /// | rio  | Rioja, La
        /// </param>
        /// <param name='fecha'>
        /// Día de elaboración (AAAA-MM-DD)
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<object>> PredicciónCCAAmedioplazoArchivoWithHttpMessagesAsync(string ccaa, string fecha, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Predicción CCAA pasado mañana. Tiempo actual.
        /// </summary>
        /// Predicción para la comunidad autónoma que se pasa como parámetro
        /// (ccaa) y validez para el medio plazo a partir de la fecha de la
        /// petición. En el caso de que en la fecha de la petición dicho
        /// producto aún no se hubiera generado retornará el último de este
        /// tipo que se hubiera generado.  Periodicidad de actualización:
        /// continuamente.
        /// <param name='ccaa'>
        /// | Código de CCAA | CCAA |
        /// |----------|----------|
        /// | and  | Andalucía   |
        /// | arn  | Aragón   |
        /// | ast  | Astrrias  |
        /// | bal  | Ballears, Illes   |
        /// | coo  | Canarias   |
        /// | can  | Cantabria   |
        /// | cle  | Castilla y León   |
        /// | clm  | Castilla - La Mancha   |
        /// | cat  | Cataluña   |
        /// | val  | Comunitat Valenciana   |
        /// | ext  | Extremadura   |
        /// | gal  | Galicia   |
        /// | mad  | Madrid, Comunidad de    |
        /// | mur  | Murcia, Región de   |
        /// | nav  | Navarra, Comunidad Foral de   |
        /// | pva  | País Vasco |
        /// | rio  | Rioja, La
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<object>> PredicciónCCAApasadomañanaTiempoactualWithHttpMessagesAsync(string ccaa, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Predicción CCAA pasado mañana. Archivo.
        /// </summary>
        /// Predicción para la comunidad autónoma que se pasa como parámetro
        /// (ccaa) y validez para pasado mañana a partir de la fecha de
        /// elaboración que se pasa como parámetro (fecha). Periodicidad de
        /// actualización: continuamente.
        /// <param name='ccaa'>
        /// | Código de CCAA | CCAA |
        /// |----------|----------|
        /// | and  | Andalucía   |
        /// | arn  | Aragón   |
        /// | ast  | Astrrias  |
        /// | bal  | Ballears, Illes   |
        /// | coo  | Canarias   |
        /// | can  | Cantabria   |
        /// | cle  | Castilla y León   |
        /// | clm  | Castilla - La Mancha   |
        /// | cat  | Cataluña   |
        /// | val  | Comunitat Valenciana   |
        /// | ext  | Extremadura   |
        /// | gal  | Galicia   |
        /// | mad  | Madrid, Comunidad de    |
        /// | mur  | Murcia, Región de   |
        /// | nav  | Navarra, Comunidad Foral de   |
        /// | pva  | País Vasco |
        /// | rio  | Rioja, La
        /// </param>
        /// <param name='fecha'>
        /// Día de elaboración (AAAA-MM-DD)
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<object>> PredicciónCCAApasadomañanaArchivoWithHttpMessagesAsync(string ccaa, string fecha, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Predicción de montaña. Tiempo pasado.
        /// </summary>
        /// Breve resumen con lo más significativo de las condiciones
        /// meteorológicas registradas en la zona de montaña que se pasa como
        /// parámetro (area) en las últimas 24-36 horas.
        /// <param name='area'>
        /// | Código de Área Montañosa | Área Montañosa |
        /// |----------|----------|
        /// | peu1 | Picos de Europa   |
        /// | nav1  | Pirineo Navarro   |
        /// | arn1  | Pirineo Aragonés  |
        /// | cat1  | Pirineo Catalán   |
        /// | rio1  | Ibérica Riojana   |
        /// | arn2  | Ibérica Aragonesa   |
        /// | mad2  | Sierras de Guadarrama y Somosierra  |
        /// | gre1  | Sierra de Gredos   |
        /// | nev1  | Sierra Nevada
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<object>> PrediccióndemontañaTiempopasadoWithHttpMessagesAsync(string area, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Predicción de montaña. Tiempo actual.
        /// </summary>
        /// Predicción meteorológica para la zona montañosa que se pasa como
        /// parámetro (area) con validez para el día (día).  Periodicidad de
        /// actualización: continuamente.
        /// <param name='area'>
        /// | Código de Área Montañosa | Área Montañosa |
        /// |----------|----------|
        /// | peu1 | Picos de Europa   |
        /// | nav1  | Pirineo Navarro   |
        /// | arn1  | Pirineo Aragonés  |
        /// | cat1  | Pirineo Catalán   |
        /// | rio1  | Ibérica Riojana   |
        /// | arn2  | Ibérica Aragonesa   |
        /// | mad2  | Sierras de Guadarrama y Somosierra  |
        /// | gre1  | Sierra de Gredos   |
        /// | nev1  | Sierra Nevada
        /// </param>
        /// <param name='dia'>
        /// | Código de día | Día |
        /// |----------|----------|
        /// | 0 | día actual  |
        /// | 1  | d+1 (mañana)   |
        /// | 2  | d+2 (pasado mañana)  |
        /// | 3  | d+3 (siguente a pasado mañana)
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<object>> PrediccióndemontañaTiempoactualWithHttpMessagesAsync(string area, string dia, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Información nivológica.
        /// </summary>
        /// Información nivológica para la zona montañosa que se pasa como
        /// parámetro (area).
        /// <param name='area'>
        /// | Código de  Área Montañosa |  Área Montañosa |
        /// |----------|----------|
        /// | 0 | Pirineo Catalán  |
        /// | 1  | Pirineo Navarro y Aragonés
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<object>> InformacionnivologicaWithHttpMessagesAsync(string area, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Predicción por municipios diaria. Tiempo actual.
        /// </summary>
        /// Predicción para el municipio que se pasa como parámetro
        /// (municipio). Periodicidad de actualización: continuamente.
        /// <param name='municipio'>
        /// Código de municipio
        /// http://www.ine.es/daco/daco42/codmun/codmunmapa.htm
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<object>> PredicciónpormunicipiosdiariaTiempoactualWithHttpMessagesAsync(string municipio, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Predicción por municipios horaria. Tiempo actual.
        /// </summary>
        /// Predicción horaria para el municipio que se pasa como parámetro
        /// (municipio). Presenta la información de hora en hora hasta 48
        /// horas.
        /// <param name='municipio'>
        /// Código de municipio
        /// http://www.ine.es/daco/daco42/codmun/codmunmapa.htm
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<object>> PredicciónpormunicipioshorariaTiempoactualWithHttpMessagesAsync(string municipio, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Predicción para las playas. Tiempo actual.
        /// </summary>
        /// La predicción diaria de la playa que se pasa como parámetro.
        /// Establece el estado de nubosidad para unas horas determinadas,
        /// las 11 y las 17 hora oficial. Se analiza también si se espera
        /// precipitación en el entorno de esas horas, entre las 08 y las 14
        /// horas y entre las 14 y 20 horas.
        /// <param name='playa'>
        /// Código de playa
        /// http://www.aemet.es/documentos/es/eltiempo/prediccion/playas/Playas_codigos.csv
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<object>> PredicciónparalasplayasTiempoactualWithHttpMessagesAsync(string playa, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Predicción de radiación ultravioleta (UVI).
        /// </summary>
        /// Predicción de Índice de radiación UV máximo en condiciones de
        /// cielo despejado para el día seleccionado.
        /// <param name='dia'>
        /// | Código de día | Día |
        /// |----------|----------|
        /// | 0 | día actual  |
        /// | 1  | d+1 (mañana)   |
        /// | 2  | d+2 (pasado mañana)  |
        /// | 3  | d+3 (dentro de 3 días) |
        /// | 4  | d+4 (dentro de 4 días)
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<object>> PredicciónderadiaciónultravioletaUVIWithHttpMessagesAsync(string dia, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Predicción marítima de alta mar.
        /// </summary>
        /// Predicción para un periodo de 24 horas de las condiciones
        /// meteorológicas para el área marítima pasada por parámetro.
        /// <param name='area'>
        /// | Código | Área de Alta Mar |
        /// |----------|----------|
        /// | 0 | Océano Atlántico al sur de 35º N   |
        /// | 1  | Océano Atlántico al norte de 30º N   |
        /// | 2  | Mar Mediterráneo
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<object>> PredicciónmarítimadealtamarWithHttpMessagesAsync(string area, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Predicción marítima costera.
        /// </summary>
        /// Predicción para un periodo de 24 horas de las condiciones
        /// meteorológicas para la zona costera pasada por parámetro.
        /// <param name='costa'>
        /// | Código | Área Costera |
        /// |----------|----------|
        /// | 42 | Costa de Andalucía Occidental y Ceuta   |
        /// | 47  | Costa de Andalucía Oriental y Melilla   |
        /// | 41  | Costa de Asturias, Cantabria y País Vasco  |
        /// | 45  | Costa de Cataluña   |
        /// | 40  | Costa de Galicia   |
        /// | 44  | Costa de Illes Balears   |
        /// | 43  | Costa de las Islas Canarias  |
        /// | 46  | Costa de Valencia y Murcia
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<object>> PredicciónmarítimacosteraWithHttpMessagesAsync(string costa, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Predicción nacional hoy. Última elaborada.
        /// </summary>
        /// Predicción nacional para el día actual a la fecha de elaboración
        /// en formato texto. Actualización diaria. Hay días en los que este
        /// producto no se realiza. En ese caso se devuelve la predicción
        /// nacional última que se elaboró.
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<object>> PredicciónnacionalhoyTiempoactualWithHttpMessagesAsync(Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Predicción nacional hoy. Archivo.
        /// </summary>
        /// Predicción nacional para el día correspondiente a la fecha que se
        /// pasa como parámetro en en formato texto. Actualización diaria.
        /// Hay días en los que este producto no se realiza. En ese caso se
        /// devuelve un 404 producto no existente.
        /// <param name='fecha'>
        /// Fecha en formato (AAAA-MM-DD)
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<object>> PredicciónnacionalhoyArchivoWithHttpMessagesAsync(string fecha, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Predicción nacional mañana. Tiempo actual.
        /// </summary>
        /// Predicción nacional para el día siguiente a la fecha de
        /// elaboración. En este caso la fecha de elaboración es el día
        /// actual. Actualización diaria. En el caso de que en el día actual
        /// todavía no se haya elaborado se devolverá el último producto de
        /// predicción nacional para mañana elaborado.
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<object>> PredicciónnacionalmañanaTiempoactualWithHttpMessagesAsync(Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Predicción nacional mañana. Archivo.
        /// </summary>
        /// Predicción nacional para el día siguiente a la fecha de
        /// elaboración. En este caso la fecha de elaboración es la fecha que
        /// se pasa como parámetro. Actualización diaria.
        /// <param name='fecha'>
        /// Día (AAAA-MM-DD)
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<object>> PredicciónnacionalmañanaArchivoWithHttpMessagesAsync(string fecha, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Predicción nacional medio plazo. Tiempo actual.
        /// </summary>
        /// Predicción nacional para medio plazo siguiente a la fecha de
        /// elaboración. En este caso la fecha de elaboración es el día
        /// actual. Actualización diaria. En el caso de que en el día actual
        /// todavía no se haya elaborado se devolverá el último producto de
        /// predicción nacional para medio plazo elaborado.
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<object>> PredicciónnacionalmedioplazoTiempoactualWithHttpMessagesAsync(Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Predicción nacional medio plazo. Archivo.
        /// </summary>
        /// Predicción nacional para el medio plazo siguiente a la fecha de
        /// elaboración. En este caso, la fecha de elaboración es la fecha
        /// que se pasa como parámetro. Actualización diaria.
        /// <param name='fecha'>
        /// Día (AAAA-MM-DD)
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<object>> PredicciónnacionalmedioplazoArchivoWithHttpMessagesAsync(string fecha, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Predicción nacional pasado mañana. Tiempo actual.
        /// </summary>
        /// Predicción nacional para pasado mañana siguiente a la fecha de
        /// elaboración. En este caso la fecha de elaboración es el día
        /// actual. Actualización diaria. En el caso de que en el día actual
        /// todavía no se haya elaborado se devolverá el último producto de
        /// predicción nacional para pasado mañana elaborado.
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<object>> PredicciónnacionalpasadomañanaTiempoactualWithHttpMessagesAsync(Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Predicción nacional pasado mañana. Archivo.
        /// </summary>
        /// Predicción nacional para pasado mañana siguiente a la fecha de
        /// elaboración. En este caso, la fecha de elaboración es la fecha
        /// que se pasa como parámetro. Actualización diaria.
        /// <param name='fecha'>
        /// Día (AAAA-MM-DD)
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<object>> PredicciónnacionalpasadomañanaArchivoWithHttpMessagesAsync(string fecha, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Predicción nacional tendencia. Tiempo actual.
        /// </summary>
        /// Predicción nacional para tendencia siguiente a la fecha de
        /// elaboración. En este caso la fecha de elaboración es el día
        /// actual. Actualización diaria. En el caso de que en el día actual
        /// todavía no se haya elaborado se devolverá el último producto de
        /// predicción nacional para tendencia elaborado.
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<object>> PredicciónnacionaltendenciaTiempoactualWithHttpMessagesAsync(Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Predicción nacional tendencia. Archivo.
        /// </summary>
        /// Predicción nacional para tendencia siguiente a la fecha de
        /// elaboración. En este caso, la fecha de elaboración es la fecha
        /// que se pasa como parámetro. Actualización diaria.
        /// <param name='fecha'>
        /// Día (AAAA-MM-DD)
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<object>> PredicciónnacionaltendenciaArchivoWithHttpMessagesAsync(string fecha, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Predicción provincia hoy. Tiempo actual.
        /// </summary>
        /// Predicción del día actual para la provincia que se pasa como
        /// parámetro. En el caso de que este producto no se haya elaborado
        /// todavía en el día actual, se retorna el último elaborado.
        /// Actualización continua y fija a las 14:00 Hora Oficial Peninsular.
        /// <param name='provincia'>
        /// | Código Provincia | Provincia |
        /// |----------|----------|
        /// | 01  | Araba/Álaba   |
        /// | 01  | Araba/Álava   |
        /// | 02  | Albacete   |
        /// | 03  | Alacant/Alicante  |
        /// | 04  | Almería   |
        /// | 33  | Asturias   |
        /// | 05  | Ávila   |
        /// | 06  | Badajoz   |
        /// | 07  | Illes Ballears   |
        /// | 08  | Barcelona   |
        /// | 48  | Bizkaia   |
        /// | 09  | Burgos   |
        /// | 10  | Cáceres   |
        /// | 11  | Cádiz   |
        /// | 39  | Cantabria   |
        /// | 12  | Castelló/Castellón   |
        /// | 51  | Ceuta   |
        /// | 13  | Ciudad Real   |
        /// | 14  | Córdoba   |
        /// | 15  | A Coruña   |
        /// | 16  | Cuenca   |
        /// | 17  | Girona   |
        /// | 18  | Granada   |
        /// | 19  | Guadalajara   |
        /// | 20  | Gipuzkoa   |
        /// | 21  | Huelva   |
        /// | 22  | Huesca   |
        /// | 23  | Jaén   |
        /// | 24  | León   |
        /// | 25  | Lleida   |
        /// | 27  | Lugo   |
        /// | 28  | Madrid   |
        /// | 29  | Málaga   |
        /// | 52  | Melilla   |
        /// | 30  | Murcia   |
        /// | 31  | Navarra   |
        /// | 32  | Oursense   |
        /// | 34  | Palencia   |
        /// | 35  | Las Palmas   |
        /// | 36  | Pontevedra   |
        /// | 26  | La Rioja   |
        /// | 37  | Salamanca   |
        /// | 38  | Santa Cruz de Tenerife   |
        /// | 40  | Segovia   |
        /// | 41  | Sevilla   |
        /// | 42  | Soria   |
        /// | 43  | Tarragona   |
        /// | 44  | Teruel   |
        /// | 45  | Toledo   |
        /// | 46  | València/Valencia   |
        /// | 47  | Valladolid   |
        /// | 49  | Zamora   |
        /// | 50  | Zaragoza   |
        /// |
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<object>> PredicciónprovinciahoyTiempoactualWithHttpMessagesAsync(string provincia, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Predicción provincia hoy. Archivo.
        /// </summary>
        /// Predicción del día siguiente a la fecha que se pasa como parámetro
        /// para la provincia que se pasa como parámetro. Actualización
        /// continua y fija a las 14:00 Hora Oficial Peninsular del día que
        /// se pasa como parámetro.
        /// <param name='provincia'>
        /// | Código Provincia | Provincia |
        /// |----------|----------|
        /// | 01  | Araba/Álaba   |
        /// | 01  | Araba/Álava   |
        /// | 02  | Albacete   |
        /// | 03  | Alacant/Alicante  |
        /// | 04  | Almería   |
        /// | 33  | Asturias   |
        /// | 05  | Ávila   |
        /// | 06  | Badajoz   |
        /// | 07  | Illes Ballears   |
        /// | 08  | Barcelona   |
        /// | 48  | Bizkaia   |
        /// | 09  | Burgos   |
        /// | 10  | Cáceres   |
        /// | 11  | Cádiz   |
        /// | 39  | Cantabria   |
        /// | 12  | Castelló/Castellón   |
        /// | 51  | Ceuta   |
        /// | 13  | Ciudad Real   |
        /// | 14  | Córdoba   |
        /// | 15  | A Coruña   |
        /// | 16  | Cuenca   |
        /// | 17  | Girona   |
        /// | 18  | Granada   |
        /// | 19  | Guadalajara   |
        /// | 20  | Gipuzkoa   |
        /// | 21  | Huelva   |
        /// | 22  | Huesca   |
        /// | 23  | Jaén   |
        /// | 24  | León   |
        /// | 25  | Lleida   |
        /// | 27  | Lugo   |
        /// | 28  | Madrid   |
        /// | 29  | Málaga   |
        /// | 52  | Melilla   |
        /// | 30  | Murcia   |
        /// | 31  | Navarra   |
        /// | 32  | Oursense   |
        /// | 34  | Palencia   |
        /// | 35  | Las Palmas   |
        /// | 36  | Pontevedra   |
        /// | 26  | La Rioja   |
        /// | 37  | Salamanca   |
        /// | 38  | Santa Cruz de Tenerife   |
        /// | 40  | Segovia   |
        /// | 41  | Sevilla   |
        /// | 42  | Soria   |
        /// | 43  | Tarragona   |
        /// | 44  | Teruel   |
        /// | 45  | Toledo   |
        /// | 46  | València/Valencia   |
        /// | 47  | Valladolid   |
        /// | 49  | Zamora   |
        /// | 50  | Zaragoza   |
        /// |
        /// </param>
        /// <param name='fecha'>
        /// Día de elaboración (AAAA-MM-DD)
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<object>> PredicciónprovinciahoyArchivoWithHttpMessagesAsync(string provincia, string fecha, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Predicción provincia mañana. Tiempo actual.
        /// </summary>
        /// Predicción del día siguiente para la provincia que se pasa como
        /// parámetro. En el caso de que este producto no se haya elaborado
        /// todavía en el día actual, se retorna el último elaborado.
        /// Actualización continua y fija a las 14:00 Hora Oficial Peninsular.
        /// <param name='provincia'>
        /// | Código Provincia | Provincia |
        /// |----------|----------|
        /// | 01  | Araba/Álaba   |
        /// | 01  | Araba/Álava   |
        /// | 02  | Albacete   |
        /// | 03  | Alacant/Alicante  |
        /// | 04  | Almería   |
        /// | 33  | Asturias   |
        /// | 05  | Ávila   |
        /// | 06  | Badajoz   |
        /// | 07  | Illes Ballears   |
        /// | 08  | Barcelona   |
        /// | 48  | Bizkaia   |
        /// | 09  | Burgos   |
        /// | 10  | Cáceres   |
        /// | 11  | Cádiz   |
        /// | 39  | Cantabria   |
        /// | 12  | Castelló/Castellón   |
        /// | 51  | Ceuta   |
        /// | 13  | Ciudad Real   |
        /// | 14  | Córdoba   |
        /// | 15  | A Coruña   |
        /// | 16  | Cuenca   |
        /// | 17  | Girona   |
        /// | 18  | Granada   |
        /// | 19  | Guadalajara   |
        /// | 20  | Gipuzkoa   |
        /// | 21  | Huelva   |
        /// | 22  | Huesca   |
        /// | 23  | Jaén   |
        /// | 24  | León   |
        /// | 25  | Lleida   |
        /// | 27  | Lugo   |
        /// | 28  | Madrid   |
        /// | 29  | Málaga   |
        /// | 52  | Melilla   |
        /// | 30  | Murcia   |
        /// | 31  | Navarra   |
        /// | 32  | Oursense   |
        /// | 34  | Palencia   |
        /// | 35  | Las Palmas   |
        /// | 36  | Pontevedra   |
        /// | 26  | La Rioja   |
        /// | 37  | Salamanca   |
        /// | 38  | Santa Cruz de Tenerife   |
        /// | 40  | Segovia   |
        /// | 41  | Sevilla   |
        /// | 42  | Soria   |
        /// | 43  | Tarragona   |
        /// | 44  | Teruel   |
        /// | 45  | Toledo   |
        /// | 46  | València/Valencia   |
        /// | 47  | Valladolid   |
        /// | 49  | Zamora   |
        /// | 50  | Zaragoza   |
        /// |
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<object>> PredicciónprovinciamañanaTiempoactualWithHttpMessagesAsync(string provincia, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Predicción provincia mañana. Archivo.
        /// </summary>
        /// Predicción del día siguiente a la fecha que se pasa como parámetro
        /// para la provincia que se pasa como parámetro. Actualización
        /// continua y fija a las 14:00 Hora Oficial Peninsular del día que
        /// se pasa como parámetro.
        /// <param name='provincia'>
        /// | Código Provincia | Provincia |
        /// |----------|----------|
        /// | 01  | Araba/Álaba   |
        /// | 01  | Araba/Álava   |
        /// | 02  | Albacete   |
        /// | 03  | Alacant/Alicante  |
        /// | 04  | Almería   |
        /// | 33  | Asturias   |
        /// | 05  | Ávila   |
        /// | 06  | Badajoz   |
        /// | 07  | Illes Ballears   |
        /// | 08  | Barcelona   |
        /// | 48  | Bizkaia   |
        /// | 09  | Burgos   |
        /// | 10  | Cáceres   |
        /// | 11  | Cádiz   |
        /// | 39  | Cantabria   |
        /// | 12  | Castelló/Castellón   |
        /// | 51  | Ceuta   |
        /// | 13  | Ciudad Real   |
        /// | 14  | Córdoba   |
        /// | 15  | A Coruña   |
        /// | 16  | Cuenca   |
        /// | 17  | Girona   |
        /// | 18  | Granada   |
        /// | 19  | Guadalajara   |
        /// | 20  | Gipuzkoa   |
        /// | 21  | Huelva   |
        /// | 22  | Huesca   |
        /// | 23  | Jaén   |
        /// | 24  | León   |
        /// | 25  | Lleida   |
        /// | 27  | Lugo   |
        /// | 28  | Madrid   |
        /// | 29  | Málaga   |
        /// | 52  | Melilla   |
        /// | 30  | Murcia   |
        /// | 31  | Navarra   |
        /// | 32  | Oursense   |
        /// | 34  | Palencia   |
        /// | 35  | Las Palmas   |
        /// | 36  | Pontevedra   |
        /// | 26  | La Rioja   |
        /// | 37  | Salamanca   |
        /// | 38  | Santa Cruz de Tenerife   |
        /// | 40  | Segovia   |
        /// | 41  | Sevilla   |
        /// | 42  | Soria   |
        /// | 43  | Tarragona   |
        /// | 44  | Teruel   |
        /// | 45  | Toledo   |
        /// | 46  | València/Valencia   |
        /// | 47  | Valladolid   |
        /// | 49  | Zamora   |
        /// | 50  | Zaragoza   |
        /// |
        /// </param>
        /// <param name='fecha'>
        /// Día de elaboración (AAAA-MM-DD)
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<object>> PredicciónprovinciamañanaArchivoWithHttpMessagesAsync(string provincia, string fecha, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Balance hídrico nacional (documento).
        /// </summary>
        /// Se obtiene, para la decema y el año pasados por parámetro, el
        /// Boletín Hídrico Nacional que se elabora cada diez días. Se
        /// presenta información resumida de forma distribuida para todo el
        /// territorio nacional de diferentes variables, en las que se
        /// incluye informaciones de la precipitación y la evapotranspiración
        /// potencial acumuladas desde el 1 de septiembre.
        /// <param name='anio'>
        /// Año (AAAA)
        /// </param>
        /// <param name='decena'>
        /// Decena de 01 (primera decena) a 36 (última decena)
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<object>> BalancehídriconacionaldocumentoWithHttpMessagesAsync(string anio, string decena, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Resumen mensual climatológico nacional (documento).
        /// </summary>
        /// Resumen climatológico nacional, para el año y mes pasado por
        /// parámetro, sobre el estado del clima y la evolución de las
        /// principales variables climáticas, en especial temperatura y
        /// precipitación, a nivel mensual, estacional y anual.
        /// <param name='anio'>
        /// Año (AAAA)
        /// </param>
        /// <param name='mes'>
        /// Mes (mm)
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<object>> ResumenmensualclimatológiconacionaldocumentoWithHttpMessagesAsync(string anio, string mes, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Capas SHAPE de estaciones climatológicas de AEMET.
        /// </summary>
        /// Capas SHAPE de las distintas estaciones climatológicas de AEMET:
        /// automáticas, completas, pluviométricas y termométricas.
        /// <param name='tipoestacion'>
        /// | Código | Tipo de Estación |
        /// |----------|----------|
        /// | automaticas  | Estaciones Automáticas   |
        /// | completas  | Estaciones Completas   |
        /// | pluviometricas  | Estaciones Pluviométricas   |
        /// | termometricas  | Estaciones Termométricas
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<object>> CapasSHAPEdeestacionesclimatológicasWithHttpMessagesAsync(string tipoestacion, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Datos de contaminación de fondo. Tiempo actual.
        /// </summary>
        /// Ficheros diarios con datos diezminutales de la estación de la red
        /// de contaminación de fondo EMEP/VAG/CAMP pasada por parámetro, de
        /// temperatura, presión, humedad, viento (dirección y velocidad),
        /// radiación global, precipitación y 4 componentes químicos:
        /// O3,SO2,NO,NO2 y PM10. Los datos se encuentran en formato FINN
        /// (propio del Ministerio de Medio Ambiente). Periodicidad: cada
        /// hora.
        /// <param name='nombreEstacion'>
        /// | Código | Estación de la Red EMEP |
        /// |----------|----------|
        /// | 11  | Barcarrota (Badajoz)   |
        /// | 10  | Cabo de Creus (Girona)   |
        /// | 09  | Campisábalos (Guadalajara)   |
        /// | 17  | Doñana (Huelva)  |
        /// | 14  | Els Torms (Lleida)   |
        /// | 06  | Mahón (Illes Balears)   |
        /// | 08  | Niembro-Llanes (Asturias)   |
        /// | 05  | Noia (A Coruña)   |
        /// | 16  | O Saviñao (Lugo)   |
        /// | 13  | Peñausende (Zamora)   |
        /// | 01  | San Pablo de los Montes (Toledo)   |
        /// | 07  | Víznar (Granada)   |
        /// | 12  | Zarra (Valencia)
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<object>> DatosdecontaminacióndefondoTiempoactualWithHttpMessagesAsync(string nombreEstacion, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Contenido total de ozono. Tiempo actual.
        /// </summary>
        /// Dato medio diario de contenido total de ozono. Cada 24 h
        /// (actualmente, en fines de semana, festivos y vacaciones no se
        /// genera por la falta de personal en el Centro Radiométrico
        /// Nacional).
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<object>> ContenidototaldeozonoTiempoactualWithHttpMessagesAsync(Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Perfiles verticales de ozono. Tiempo actual.
        /// </summary>
        /// Perfil Vertical de Ozono de la estación pasada por parámetro.
        /// Periodicidad: cada 7 días.
        /// <param name='estacion'>
        /// | Código | Estación |
        /// |----------|----------|
        /// | canarias  | Izaña   |
        /// | peninsula  | Madrid
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<object>> PerfilesverticalesdeozonoTiempoactualWithHttpMessagesAsync(string estacion, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Datos de radiación global, directa o difusa. Tiempo actual.
        /// </summary>
        /// Datos horarios (HORA SOLAR VERDADERA) acumulados de radiación
        /// global, directa, difusa e infrarroja, y datos semihorarios
        /// (HORA SOLAR VERDADERA) acumulados de radiación ultravioleta
        /// eritemática.Datos diarios acumulados  de radiación global,
        /// directa, difusa, ultravioleta eritemática e infrarroja.
        /// Periodicidad: Cada 24h (actualmente en fines de semana, festivos
        /// y vacaciones, no se genera por la ausencia de personal en el
        /// Centro Radiométrico Nacional).
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<object>> DatosderadiaciónglobaldirectaodifusaTiempoactualWithHttpMessagesAsync(Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Imagen composición nacional radares. Tiempo actual estándar.
        /// </summary>
        /// Imagen composición nacional radares. Tiempo actual estándar.
        /// Periodicidad: 30 minutos.
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<object>> ImagencomposiciónnacionalradaresTiempoactualestándarWithHttpMessagesAsync(Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Imagen gráfica radar regional. Tiempo actual estándar.
        /// </summary>
        /// Imagen del radar regional de la región pasada por parámetro.
        /// Tiempo actual estándar. Periodicidad: 10 minutos.
        /// <param name='radar'>
        /// | Código | Radar |
        /// |----------|----------|
        /// | am  | Almería   |
        /// | sa  | Asturias   |
        /// | pm  | Illes Balears   |
        /// | ba  | Barcelona  |
        /// | cc  | Cáceres   |
        /// | co  | A Coruña   |
        /// | ma  | Madrid   |
        /// | ml  | Málaga   |
        /// | mu  | Murcia   |
        /// | vd  | Palencia   |
        /// | ca  | Las Palmas   |
        /// | se  | Sevilla   |
        /// | va  | Valencia   |
        /// | ss  | Vizcaya   |
        /// | za  | Zaragoza
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<object>> RadarRegionalWithHttpMessagesAsync(string radar, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Mapa con los rayos registrados en periodo standard. Último
        /// elaborado.
        /// </summary>
        /// Imagen de las descargas caídas en el territorio nacional durante
        /// un período de 12 horas.
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<object>> MapaconlosrayosregistradosenperiodostandardÚltimoelaboradoWithHttpMessagesAsync(Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Índice normalizado de vegetación.
        /// </summary>
        /// Esta imagen se realiza con una combinación de los datos del canal
        /// visible y del infrarrojo cercano del satélite NOAA-19, que nos da
        /// una idea del desarrollo de la vegetación. Esto es así debido a
        /// que la vegetación absorbe fuertemente la radiación del canal
        /// visible, pero refleja fuertemente la del infrarrojo cercano. Esta
        /// imagen se renueva los jueves a última hora y contiene los datos
        /// acumulados de la última semana.
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<object>> ÍndicenormalizadodevegetaciónWithHttpMessagesAsync(Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Temperatura del agua del mar.
        /// </summary>
        /// Imagen obtenida con una combinación de los datos de los canales
        /// infrarrojos del satélite NOAA-19, que nos da la temperatura de la
        /// superficie del mar. Esta imagen se renueva todos los días a
        /// última hora y contiene los datos acumulados de los últimos siete
        /// días.
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<object>> TemperaturadelaguadelmarWithHttpMessagesAsync(Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Climatologías diarias.
        /// </summary>
        /// Valores climatológicos para el rango de fechas y la estación
        /// seleccionada. Periodicidad: 1 vez al día.
        /// <param name='fechaIniStr'>
        /// Fecha Inicial (AAAA-MM-DDTHH:MM:SSUTC)
        /// </param>
        /// <param name='fechaFinStr'>
        /// Fecha Final (AAAA-MM-DDTHH:MM:SSUTC)
        /// </param>
        /// <param name='idema'>
        /// Indicativo climatológico de la EMA. Puede introducir varios
        /// indicativos separados por comas (,)
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<object>> ClimatologíasdiariasWithHttpMessagesAsync(string fechaIniStr, string fechaFinStr, string idema, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Estaciones por indicativo.
        /// </summary>
        /// Características de la estación climatológica pasada por parámetro.
        /// <param name='estaciones'>
        /// Listado de indicativos climatológicos (id1,id2,id3,...,idn)
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<object>> EstacionesporindicativoWithHttpMessagesAsync(string estaciones, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Inventario de estaciones (valores climatológicos).
        /// </summary>
        /// Inventario con las características de todas las estaciones
        /// climatológicas. Periodicidad: 1 vez al día.
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<object>> InventariodeestacionesvaloresclimatológicosWithHttpMessagesAsync(Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Climatologías mensuales anuales.
        /// </summary>
        /// Valores medios mensuales y anuales de los datos climatológicos
        /// para la estación y el periodo de años pasados por parámetro.
        /// Periodicidad: 1 vez al día.
        /// <param name='anioIniStr'>
        /// Año Inicial (AAAA)
        /// </param>
        /// <param name='anioFinStr'>
        /// Año Final (AAAA)
        /// </param>
        /// <param name='idema'>
        /// Indicativo climatológico de la EMA
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<object>> ClimatologíasmensualesanualesWithHttpMessagesAsync(string anioIniStr, string anioFinStr, string idema, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Climatologías normales (1981-2010).
        /// </summary>
        /// Valores climatológicos normales (periodo 1981-2010) para la
        /// estación pasada por parámetro. Periodicidad: 1 vez al día.
        /// <param name='idema'>
        /// Indicativo climatológico de la EMA
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<object>> Climatologíasnormales19812010WithHttpMessagesAsync(string idema, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Valores extremos.
        /// </summary>
        /// Valores extremos para la estación y la variable (precipitación,
        /// temperatura y viento) pasadas por parámetro. Periodicidad: 1 vez
        /// al día.
        /// <param name='parametro'>
        /// | Código | Parámetro Meteorológico |
        /// |----------|----------|
        /// | P  | Precipitación   |
        /// | T  | Temperatura   |
        /// | V  | Viento
        /// </param>
        /// <param name='idema'>
        /// Indicativo climatológico de la EMA
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<object>> ValoresextremosWithHttpMessagesAsync(string parametro, string idema, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

    }
}
