// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace UnicarAdmin
{
    using System;
    using System.Collections.Generic;
    using System.Net.Http;
    using System.Threading;
    using System.Threading.Tasks;
    using Microsoft.Rest;
    using DefaultConnection;

    /// <summary>
    /// Climatologíasdiarias operations.
    /// </summary>
    public partial interface IClimatologíasdiarias
    {
        /// <summary>
        /// Climatologías diarias.
        /// </summary>
        /// Valores climatológicos de todas las estaciones para el rango de
        /// fechas seleccionado. Periodicidad: 1 vez al día.
        /// <param name='fechaIniStr'>
        /// Fecha Inicial (AAAA-MM-DDTHH:MM:SSUTC)
        /// </param>
        /// <param name='fechaFinStr'>
        /// Fecha Final (AAAA-MM-DDTHH:MM:SSUTC)
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<object>> OneWithHttpMessagesAsync(string fechaIniStr, string fechaFinStr, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));
    }
}
