// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace UnicarAdmin
{
    using System;
    using System.Collections.Generic;
    using System.Net.Http;
    using System.Threading;
    using System.Threading.Tasks;
    using Microsoft.Rest;
    using DefaultConnection;

    /// <summary>
    /// DatosdeobservaciónTiempoactual operations.
    /// </summary>
    public partial interface IDatosdeobservaciónTiempoactual
    {
        /// <summary>
        /// Datos de observación. Tiempo actual.
        /// </summary>
        /// Datos de observación horarios de las últimas 24 horas de la
        /// estación meterológica que se pasa como parámetro (idema).
        /// Frecuencia de actualización: continuamente.
        /// <param name='idema'>
        /// Índicativo climatológico de la EMA
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<object>> OneWithHttpMessagesAsync(string idema, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));
    }
}
