// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace UnicarAdmin.DefaultConnection
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class FourZeroOne
    {
        /// <summary>
        /// Initializes a new instance of the FourZeroOne class.
        /// </summary>
        public FourZeroOne() { }

        /// <summary>
        /// Initializes a new instance of the FourZeroOne class.
        /// </summary>
        public FourZeroOne(string descripcion, int estado)
        {
            Descripcion = descripcion;
            Estado = estado;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "descripcion")]
        public string Descripcion { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "estado")]
        public int Estado { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            if (Descripcion == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Descripcion");
            }
        }
    }
}
